name: CI

on: workflow_dispatch

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/Checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GCP Artifact Registory
              env:
                GCP_ARTIFACT_REGISTRY_TOKEN: ${{ secrets.GCP_ARTIFACT_REGISTRY_TOKEN }}
              run: echo "${{ secrets.GCP_ARTIFACT_REGISTRY_TOKEN }} | docker login -u _json_key --password-stdin https://asia-northeast1-docker.pkg.dev"
            
            - name: Build and Push Docker Image
              run: |
                docker build -t asia-northeast1-docker.pkg.dev/peerless-fabric-445801-p9/self-hosted-runner/test-app:latest .
                docker push asia-northeast1-docker.pkg.dev/peerless-fabric-445801-p9/self-hosted-runner/test-app:latest
            
            - name: Run Docker Conteiner and Execute Tests
              run: |
                docker run --rm asia-northeast1-docker.pkg.dev/peerless-fabric-445801-p9/self-hosted-runner/test-app:latest